CREATE TABLE hosts
	(macid CHAR(17), macvendor VARCHAR(25),
	ip VARCHAR(15), hostname VARCHAR(100),
	updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
	id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE ports
	(id INT AUTO_INCREMENT PRIMARY KEY,
	host_id INT NOT NULL, state VARCHAR(6),
	port INT, protocol VARCHAR(3), service VARCHAR(25),
	FOREIGN KEY(host_id) REFERENCES hosts(id));
CREATE TABLE os
	(id INT AUTO_INCREMENT PRIMARY KEY,
	cpe VARCHAR(50), osname VARCHAR (50), accuracy INT,
	FOREIGN KEY(host_id) REFERENCES hosts(id));
CREATE TABLE oid
    (id INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY(oid_id) REFERENCES oids(id),
    FOREIGN KEY(host_id) REFERENCES hosts(id));